name: CI for All Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typing-indicator-service:
    name: Typing Indicator Service CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/typing-indicator-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 app

    - name: Check Python formatting with black
      run: |
        pip install black
        black --check app

    - name: Run tests (if any)
      run: |
        echo "Add test commands here, e.g., pytest"

  # Repeat for other services if needed, or use a matrix

  # Example: chat-service
  # chat-service:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: services/chat-service
  #   steps:
  #     ...

